# Generated by Django 5.1.4 on 2025-01-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dictionary',
            new_name='DictEntry',
        ),
        migrations.AlterModelOptions(
            name='dictentry',
            options={'verbose_name_plural': 'Dictionary'},
        ),
    ]
