# Generated by Django 5.1.4 on 2025-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_dictionary_dictentry_alter_dictentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictentry',
            options={'verbose_name_plural': 'Dict entries'},
        ),
        migrations.AddField(
            model_name='dictentry',
            name='reading',
            field=models.CharField(default='None', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictentry',
            name='word',
            field=models.CharField(max_length=32),
        ),
    ]
