# Generated by Django 5.1.4 on 2025-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_tag_card_tags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictentry',
            index=models.Index(fields=['id'], name='cards_dicte_id_7d2e82_idx'),
        ),
        migrations.AddIndex(
            model_name='dictentry',
            index=models.Index(fields=['word'], name='cards_dicte_word_1b31ca_idx'),
        ),
    ]
