# Generated by Django 5.1.4 on 2025-01-08 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_tag_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('strokes', models.PositiveSmallIntegerField()),
                ('meanings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('kun', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('on', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('strokes', models.PositiveSmallIntegerField()),
                ('meanings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('kun', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('on', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('radicals', models.ManyToManyField(related_name='kanji', to='cards.radical')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
