# Generated by Django 5.1.4 on 2025-01-13 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_dictentry_kanji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='radicals',
        ),
        migrations.AddField(
            model_name='kanji',
            name='name_readings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dictentry',
            name='kanji',
            field=models.ManyToManyField(blank=True, related_name='words', to='cards.kanji'),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kun',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Radical',
        ),
    ]
