# Generated by Django 5.1.4 on 2025-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_kanji_radicals_kanji_name_readings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanji',
            options={'verbose_name_plural': 'Kanji'},
        ),
        migrations.AddIndex(
            model_name='kanji',
            index=models.Index(fields=['id'], name='cards_kanji_id_f7ccd9_idx'),
        ),
        migrations.AddIndex(
            model_name='kanji',
            index=models.Index(fields=['character'], name='cards_kanji_charact_b1ef53_idx'),
        ),
    ]
