# Generated by Django 5.1.4 on 2025-01-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_kanji_options_kanji_cards_kanji_id_f7ccd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.tag'),
        ),
    ]
