# Generated by Django 5.1.4 on 2025-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_card_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
