# Generated by Django 5.1.4 on 2025-02-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_card_examples_deck_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='cards.card'),
        ),
    ]
