# Generated by Django 5.1.4 on 2025-02-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_remove_card_deck_deck_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_relations', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations', to='cards.deck')),
            ],
        ),
        migrations.RemoveField(
            model_name="deck",
            name="cards",
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='cards.DeckCardRelation', to='cards.card'),
        ),
    ]
