# Generated by Django 5.1.4 on 2025-02-11 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_deckcardrelation_alter_deck_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='examples',
        ),
        migrations.AddField(
            model_name='deckcardrelation',
            name='examples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=['Example'], size=None),
            preserve_default=False,
        ),
    ]
