# Generated by Django 5.1.4 on 2025-02-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_remove_card_examples_deckcardrelation_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='parent',
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='SubDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cards', models.ManyToManyField(through='cards.DeckCardRelation', to='cards.card')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_decks', to='cards.deck')),
            ],
        ),
        migrations.AlterField(
            model_name='deckcardrelation',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations', to='cards.subdeck'),
        ),
    ]
