# Generated by Django 5.1.4 on 2025-02-11 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_remove_deck_cards_remove_deck_parent_alter_deck_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together={('user', 'name')},
        ),
    ]
